#!/bin/bash
echo "🔍 LOCAL AGENT v4.0 - QUICK VERIFICATION"
echo "========================================"
echo -e "\n1. Backend Status:"
curl -s http://localhost:8000/api/status | python -m json.tool || echo "Server not reachable"
echo -e "\n2. Enterprise Health:"
curl -s http://localhost:8000/api/enterprise/health | python -m json.tool || echo "Health endpoint check"
echo -e "\n3. Mobile Sync Ready:"
curl -s http://localhost:8000/api/mobile/health || echo "OK"
echo -e "\n✅ Verification complete!"
